# Generated by Django 3.1.7 on 2021-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_table',
            name='client',
        ),
        migrations.AddField(
            model_name='count_table',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
