# Generated by Django 3.0.7 on 2021-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_name',
            field=models.CharField(choices=[('Reliance LTD', 'Reliance LTD'), ('Timex Belting', 'Timex Belting'), ('MS Brothers', 'MS Brothers'), ('3i Infotech', '3i Infotech'), ('V Paras Corp', 'V Paras Corp'), ('AP Enterprises', 'AP Enterprises')], default='', max_length=40, verbose_name="Seller's name"),
        ),
    ]
